# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/tools/cmake/3.8.0/bin/cmake

# The command to remove a file.
RM = /opt/tools/cmake/3.8.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shijia/Public/ScDebug

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shijia/Public/ScDebug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/tools/cmake/3.8.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shijia/Public/ScDebug/CMakeFiles /home/shijia/Public/ScDebug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shijia/Public/ScDebug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ext

# Build rule for target.
ext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ext
.PHONY : ext

# fast build rule for target.
ext/fast:
	$(MAKE) -f CMakeFiles/ext.dir/build.make CMakeFiles/ext.dir/build
.PHONY : ext/fast

#=============================================================================
# Target rules for targets named tacstmt

# Build rule for target.
tacstmt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tacstmt
.PHONY : tacstmt

# fast build rule for target.
tacstmt/fast:
	$(MAKE) -f CMakeFiles/tacstmt.dir/build.make CMakeFiles/tacstmt.dir/build
.PHONY : tacstmt/fast

#=============================================================================
# Target rules for targets named tacop

# Build rule for target.
tacop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tacop
.PHONY : tacop

# fast build rule for target.
tacop/fast:
	$(MAKE) -f CMakeFiles/tacop.dir/build.make CMakeFiles/tacop.dir/build
.PHONY : tacop/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named insp

# Build rule for target.
insp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 insp
.PHONY : insp

# fast build rule for target.
insp/fast:
	$(MAKE) -f CMakeFiles/insp.dir/build.make CMakeFiles/insp.dir/build
.PHONY : insp/fast

#=============================================================================
# Target rules for targets named transblock

# Build rule for target.
transblock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transblock
.PHONY : transblock

# fast build rule for target.
transblock/fast:
	$(MAKE) -f CMakeFiles/transblock.dir/build.make CMakeFiles/transblock.dir/build
.PHONY : transblock/fast

#=============================================================================
# Target rules for targets named partion

# Build rule for target.
partion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partion
.PHONY : partion

# fast build rule for target.
partion/fast:
	$(MAKE) -f CMakeFiles/partion.dir/build.make CMakeFiles/partion.dir/build
.PHONY : partion/fast

#=============================================================================
# Target rules for targets named tac

# Build rule for target.
tac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tac
.PHONY : tac

# fast build rule for target.
tac/fast:
	$(MAKE) -f CMakeFiles/tac.dir/build.make CMakeFiles/tac.dir/build
.PHONY : tac/fast

src/extr/ExtractStmt.o: src/extr/ExtractStmt.cpp.o

.PHONY : src/extr/ExtractStmt.o

# target to build an object file
src/extr/ExtractStmt.cpp.o:
	$(MAKE) -f CMakeFiles/ext.dir/build.make CMakeFiles/ext.dir/src/extr/ExtractStmt.cpp.o
.PHONY : src/extr/ExtractStmt.cpp.o

src/extr/ExtractStmt.i: src/extr/ExtractStmt.cpp.i

.PHONY : src/extr/ExtractStmt.i

# target to preprocess a source file
src/extr/ExtractStmt.cpp.i:
	$(MAKE) -f CMakeFiles/ext.dir/build.make CMakeFiles/ext.dir/src/extr/ExtractStmt.cpp.i
.PHONY : src/extr/ExtractStmt.cpp.i

src/extr/ExtractStmt.s: src/extr/ExtractStmt.cpp.s

.PHONY : src/extr/ExtractStmt.s

# target to generate assembly for a file
src/extr/ExtractStmt.cpp.s:
	$(MAKE) -f CMakeFiles/ext.dir/build.make CMakeFiles/ext.dir/src/extr/ExtractStmt.cpp.s
.PHONY : src/extr/ExtractStmt.cpp.s

src/insert/InsertParen.o: src/insert/InsertParen.cpp.o

.PHONY : src/insert/InsertParen.o

# target to build an object file
src/insert/InsertParen.cpp.o:
	$(MAKE) -f CMakeFiles/insp.dir/build.make CMakeFiles/insp.dir/src/insert/InsertParen.cpp.o
.PHONY : src/insert/InsertParen.cpp.o

src/insert/InsertParen.i: src/insert/InsertParen.cpp.i

.PHONY : src/insert/InsertParen.i

# target to preprocess a source file
src/insert/InsertParen.cpp.i:
	$(MAKE) -f CMakeFiles/insp.dir/build.make CMakeFiles/insp.dir/src/insert/InsertParen.cpp.i
.PHONY : src/insert/InsertParen.cpp.i

src/insert/InsertParen.s: src/insert/InsertParen.cpp.s

.PHONY : src/insert/InsertParen.s

# target to generate assembly for a file
src/insert/InsertParen.cpp.s:
	$(MAKE) -f CMakeFiles/insp.dir/build.make CMakeFiles/insp.dir/src/insert/InsertParen.cpp.s
.PHONY : src/insert/InsertParen.cpp.s

src/main/main.o: src/main/main.cpp.o

.PHONY : src/main/main.o

# target to build an object file
src/main/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/main.cpp.o
.PHONY : src/main/main.cpp.o

src/main/main.i: src/main/main.cpp.i

.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/main.cpp.i
.PHONY : src/main/main.cpp.i

src/main/main.s: src/main/main.cpp.s

.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main/main.cpp.s
.PHONY : src/main/main.cpp.s

src/partion/PartionStmt.o: src/partion/PartionStmt.cpp.o

.PHONY : src/partion/PartionStmt.o

# target to build an object file
src/partion/PartionStmt.cpp.o:
	$(MAKE) -f CMakeFiles/partion.dir/build.make CMakeFiles/partion.dir/src/partion/PartionStmt.cpp.o
.PHONY : src/partion/PartionStmt.cpp.o

src/partion/PartionStmt.i: src/partion/PartionStmt.cpp.i

.PHONY : src/partion/PartionStmt.i

# target to preprocess a source file
src/partion/PartionStmt.cpp.i:
	$(MAKE) -f CMakeFiles/partion.dir/build.make CMakeFiles/partion.dir/src/partion/PartionStmt.cpp.i
.PHONY : src/partion/PartionStmt.cpp.i

src/partion/PartionStmt.s: src/partion/PartionStmt.cpp.s

.PHONY : src/partion/PartionStmt.s

# target to generate assembly for a file
src/partion/PartionStmt.cpp.s:
	$(MAKE) -f CMakeFiles/partion.dir/build.make CMakeFiles/partion.dir/src/partion/PartionStmt.cpp.s
.PHONY : src/partion/PartionStmt.cpp.s

src/trans/TACTransform.o: src/trans/TACTransform.cpp.o

.PHONY : src/trans/TACTransform.o

# target to build an object file
src/trans/TACTransform.cpp.o:
	$(MAKE) -f CMakeFiles/tac.dir/build.make CMakeFiles/tac.dir/src/trans/TACTransform.cpp.o
.PHONY : src/trans/TACTransform.cpp.o

src/trans/TACTransform.i: src/trans/TACTransform.cpp.i

.PHONY : src/trans/TACTransform.i

# target to preprocess a source file
src/trans/TACTransform.cpp.i:
	$(MAKE) -f CMakeFiles/tac.dir/build.make CMakeFiles/tac.dir/src/trans/TACTransform.cpp.i
.PHONY : src/trans/TACTransform.cpp.i

src/trans/TACTransform.s: src/trans/TACTransform.cpp.s

.PHONY : src/trans/TACTransform.s

# target to generate assembly for a file
src/trans/TACTransform.cpp.s:
	$(MAKE) -f CMakeFiles/tac.dir/build.make CMakeFiles/tac.dir/src/trans/TACTransform.cpp.s
.PHONY : src/trans/TACTransform.cpp.s

src/transblock/TACTransBlockform.o: src/transblock/TACTransBlockform.cpp.o

.PHONY : src/transblock/TACTransBlockform.o

# target to build an object file
src/transblock/TACTransBlockform.cpp.o:
	$(MAKE) -f CMakeFiles/transblock.dir/build.make CMakeFiles/transblock.dir/src/transblock/TACTransBlockform.cpp.o
.PHONY : src/transblock/TACTransBlockform.cpp.o

src/transblock/TACTransBlockform.i: src/transblock/TACTransBlockform.cpp.i

.PHONY : src/transblock/TACTransBlockform.i

# target to preprocess a source file
src/transblock/TACTransBlockform.cpp.i:
	$(MAKE) -f CMakeFiles/transblock.dir/build.make CMakeFiles/transblock.dir/src/transblock/TACTransBlockform.cpp.i
.PHONY : src/transblock/TACTransBlockform.cpp.i

src/transblock/TACTransBlockform.s: src/transblock/TACTransBlockform.cpp.s

.PHONY : src/transblock/TACTransBlockform.s

# target to generate assembly for a file
src/transblock/TACTransBlockform.cpp.s:
	$(MAKE) -f CMakeFiles/transblock.dir/build.make CMakeFiles/transblock.dir/src/transblock/TACTransBlockform.cpp.s
.PHONY : src/transblock/TACTransBlockform.cpp.s

src/transop/TACTransOpform.o: src/transop/TACTransOpform.cpp.o

.PHONY : src/transop/TACTransOpform.o

# target to build an object file
src/transop/TACTransOpform.cpp.o:
	$(MAKE) -f CMakeFiles/tacop.dir/build.make CMakeFiles/tacop.dir/src/transop/TACTransOpform.cpp.o
.PHONY : src/transop/TACTransOpform.cpp.o

src/transop/TACTransOpform.i: src/transop/TACTransOpform.cpp.i

.PHONY : src/transop/TACTransOpform.i

# target to preprocess a source file
src/transop/TACTransOpform.cpp.i:
	$(MAKE) -f CMakeFiles/tacop.dir/build.make CMakeFiles/tacop.dir/src/transop/TACTransOpform.cpp.i
.PHONY : src/transop/TACTransOpform.cpp.i

src/transop/TACTransOpform.s: src/transop/TACTransOpform.cpp.s

.PHONY : src/transop/TACTransOpform.s

# target to generate assembly for a file
src/transop/TACTransOpform.cpp.s:
	$(MAKE) -f CMakeFiles/tacop.dir/build.make CMakeFiles/tacop.dir/src/transop/TACTransOpform.cpp.s
.PHONY : src/transop/TACTransOpform.cpp.s

src/transstmt/TACTransStmtform.o: src/transstmt/TACTransStmtform.cpp.o

.PHONY : src/transstmt/TACTransStmtform.o

# target to build an object file
src/transstmt/TACTransStmtform.cpp.o:
	$(MAKE) -f CMakeFiles/tacstmt.dir/build.make CMakeFiles/tacstmt.dir/src/transstmt/TACTransStmtform.cpp.o
.PHONY : src/transstmt/TACTransStmtform.cpp.o

src/transstmt/TACTransStmtform.i: src/transstmt/TACTransStmtform.cpp.i

.PHONY : src/transstmt/TACTransStmtform.i

# target to preprocess a source file
src/transstmt/TACTransStmtform.cpp.i:
	$(MAKE) -f CMakeFiles/tacstmt.dir/build.make CMakeFiles/tacstmt.dir/src/transstmt/TACTransStmtform.cpp.i
.PHONY : src/transstmt/TACTransStmtform.cpp.i

src/transstmt/TACTransStmtform.s: src/transstmt/TACTransStmtform.cpp.s

.PHONY : src/transstmt/TACTransStmtform.s

# target to generate assembly for a file
src/transstmt/TACTransStmtform.cpp.s:
	$(MAKE) -f CMakeFiles/tacstmt.dir/build.make CMakeFiles/tacstmt.dir/src/transstmt/TACTransStmtform.cpp.s
.PHONY : src/transstmt/TACTransStmtform.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ext"
	@echo "... tacstmt"
	@echo "... edit_cache"
	@echo "... tacop"
	@echo "... main"
	@echo "... insp"
	@echo "... transblock"
	@echo "... partion"
	@echo "... tac"
	@echo "... src/extr/ExtractStmt.o"
	@echo "... src/extr/ExtractStmt.i"
	@echo "... src/extr/ExtractStmt.s"
	@echo "... src/insert/InsertParen.o"
	@echo "... src/insert/InsertParen.i"
	@echo "... src/insert/InsertParen.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
	@echo "... src/partion/PartionStmt.o"
	@echo "... src/partion/PartionStmt.i"
	@echo "... src/partion/PartionStmt.s"
	@echo "... src/trans/TACTransform.o"
	@echo "... src/trans/TACTransform.i"
	@echo "... src/trans/TACTransform.s"
	@echo "... src/transblock/TACTransBlockform.o"
	@echo "... src/transblock/TACTransBlockform.i"
	@echo "... src/transblock/TACTransBlockform.s"
	@echo "... src/transop/TACTransOpform.o"
	@echo "... src/transop/TACTransOpform.i"
	@echo "... src/transop/TACTransOpform.s"
	@echo "... src/transstmt/TACTransStmtform.o"
	@echo "... src/transstmt/TACTransStmtform.i"
	@echo "... src/transstmt/TACTransStmtform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

